theme: jekyll-theme-cayman
title: GenshinWikiBot
email: geshinwikibot22@gmail.com
description: A Genshin Impact Wiki bot that gives you info about the game such, as weapons, characters, artifacts, places and more.
author: XxP404xX/Ivan Ngu
twitter_username: genshinwikibot
github_username:  XxP404xX

