theme: jekyll-theme-cayman
title: GenshinWikiBot
description: A Genshin Impact Wiki bot that gives you info about the game such, as weapons, characters, artifacts, places and more.
author: XxP404xX/Ivan Ngu
avatar: "/assests/e2802709de402a3d6648849a57e0e0a5.png"
