title: GenshinWikiBot
description: A Genshin Impact Wiki bot that gives you info about the game such, as weapons, characters, artifacts, places and more.
email: geshinwikibot22@gmail.com
author: XxP404xX/Ivan Ngu
twitter_username: genshinwikibot
github_username:  XxP404xX
theme: minima
use_logo: true
logo: assests/logo.png
avatar: "assests/logo.png"
round_avatar: true
